### ISSUE TITLE
Prover error: ; :rlimit line: 64 position: 1

### ISSUE THREAD

**Issue by 0sidharth** [boogie-org/boogie#784] opened 2023-09-17 04:19 UTC
Hi, trying to run boogie on a docker (Ubuntu 16.04). Cloned from source and built using dotnet6.0. Trying out boogie for a simple bpl file, which works on my system outside docker (Ubuntu 18.04, where I installed boogie using snap. Here is the bpl file - 

```
type Pair S T;
const p: Pair int int;

function pair<S, T>(s:S, t:T) returns(Pair S T);
function first<S, T>(p: Pair S T) returns(S);
function second<S, T>(p: Pair S T) returns(T);

axiom (forall<S, T> s:S, t:T :: {pair(s, t)} first(pair(s,t)) == s);
axiom (forall<S, T> s:S, t:T :: {pair(s, t)} second(pair(s,t)) == t);
axiom (forall<S, T> p:Pair S T :: {first(p)}{second(p)} pair(first(p), second(p)) == p);

procedure test() {
    assert first(pair(1, 2)) == 1;
    assert second(pair(1, 2)) == 2;
    assert (forall p: (Pair int int), q: (Pair int int) ::
       first(p) == first(q) && second(p) == second(q) ==> p == q);
}
```
I run it with the following command on docker - 
```
root@tv:~/boogie/Source/BoogieDriver/bin/Debug/net6.0# ./BoogieDriver /home/tv/test2.bpl /trace /proverOpt:PROVER_NAME=z3 /proverOpt:VERBOSITY=1 /proverOpt:LOG_FILE=test2.model
```
And get the following output - 
```
Parsing /home/tv/test2.bpl
Coalescing blocks...
Inlining...

Verifying test ...
[TRACE] Using prover: z3
[SMT-0] Starting z3 -smt2 -in
[SMT-OUT-0] unsat
[SMT-OUT-0] unsupported
[SMT-ERR-0] ; :rlimit line: 55 position: 1
Prover error: ; :rlimit line: 55 position: 1

Unhandled exception. System.AggregateException: One or more errors occurred. (Request returned no response)
 ---> System.Exception: Request returned no response
   at Microsoft.Boogie.SMTLib.SMTLibProcess.SendRequest(String request, CancellationToken cancellationToken) in /root/boogie/Source/Provers/SMTLib/SMTLibProcess.cs:line 148
   at Microsoft.Boogie.SMTLib.SMTLibInteractiveTheoremProver.GetRCount() in /root/boogie/Source/Provers/SMTLib/SMTLibInteractiveTheoremProver.cs:line 689
   at VC.Split.ReadOutcome(Int32 iteration, Checker checker, VerifierCallback callback) in /root/boogie/Source/VCGeneration/Split.cs:line 1287
   at VC.SplitAndVerifyWorker.ProcessResultAndReleaseChecker(Int32 iteration, Split split, Checker checker, CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/SplitAndVerifyWorker.cs:line 169
   at VC.SplitAndVerifyWorker.DoWork(Int32 iteration, Split split, CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/SplitAndVerifyWorker.cs:line 132
   at VC.SplitAndVerifyWorker.DoWork(Int32 iteration, Split split, CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/SplitAndVerifyWorker.cs:line 137
   at VC.SplitAndVerifyWorker.DoWorkForMultipleIterations(Split split, CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/SplitAndVerifyWorker.cs:line 121
   at VC.SplitAndVerifyWorker.WorkUntilDone(CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/SplitAndVerifyWorker.cs:line 85
   at VC.VCGen.VerifyImplementation(ImplementationRun run, VerifierCallback callback, CancellationToken cancellationToken, IObserver`1 batchCompletedObserver) in /root/boogie/Source/VCGeneration/VCGen.cs:line 420
   at VC.ConditionGeneration.VerifyImplementation(ImplementationRun run, IObserver`1 batchCompletedObserver, CancellationToken cancellationToken) in /root/boogie/Source/VCGeneration/ConditionGeneration.cs:line 133
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass47_0.<<VerifyImplementationWithoutCaching>b__0>d.MoveNext() in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 876
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass38_0.<<VerifyEachImplementation>b__1>d.MoveNext() in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 653
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass38_0.<<VerifyEachImplementation>b__1>d.MoveNext() in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 657
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.VerifyEachImplementation(TextWriter output, ProcessedProgram processedProgram, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId, Implementation[] stablePrioritizedImpls) in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 662
   at Microsoft.Boogie.ExecutionEngine.InferAndVerify(TextWriter output, Program program, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId) in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 564
   at Microsoft.Boogie.ExecutionEngine.ProcessProgram(TextWriter output, Program program, String bplFileName, String programId) in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 171
   at Microsoft.Boogie.ExecutionEngine.ProcessFiles(TextWriter output, IList`1 fileNames, Boolean lookForSnapshots, String programId) in /root/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 123
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Boogie.OnlyBoogie.Main(String[] args) in /root/boogie/Source/BoogieDriver/BoogieDriver.cs:line 66
Aborted (core dumped)
```
Here is the test2.model file created (which is only 48 lines, whereas the prover error complains about line 55)
```
(set-option :print-success false)
(set-info :smt-lib-version 2.6)
(set-option :smt.mbqi false)
(set-option :model.compact false)
(set-option :model.v2 true)
(set-option :pp.bv_literals false)
; done setting options


(declare-fun tickleBool (Bool) Bool)
(assert (and (tickleBool true) (tickleBool false)))
(declare-sort T@Pair_15_16 0)
(declare-fun pair_3_3 (Int Int) T@Pair_15_16)
(declare-fun first_3_3 (T@Pair_15_16) Int)
(declare-fun second_3_3 (T@Pair_15_16) Int)
(assert (forall ((s Int) (t Int) ) (! (= (first_3_3 (pair_3_3 s t)) s)
 :qid |test2bpl.8:21|
 :skolemid |0|
 :pattern ( (pair_3_3 s t))
)))
(assert (forall ((s@@0 Int) (t@@0 Int) ) (! (= (second_3_3 (pair_3_3 s@@0 t@@0)) t@@0)
 :qid |test2bpl.9:21|
 :skolemid |1|
 :pattern ( (pair_3_3 s@@0 t@@0))
)))
(assert (forall ((p T@Pair_15_16) ) (! (= (pair_3_3 (first_3_3 p) (second_3_3 p)) p)
 :qid |test2bpl.10:21|
 :skolemid |2|
 :pattern ( (first_3_3 p))
 :pattern ( (second_3_3 p))
)))
(push 1)
(declare-fun ControlFlow (Int Int) Int)
(set-info :boogie-vc-id test)
(set-option :timeout 0)
(set-option :rlimit 0)
(assert (not
 (=> (= (ControlFlow 0 0) 5) (let ((anon0_correct  (and (=> (= (ControlFlow 0 2) (- 0 4)) (= (first_3_3 (pair_3_3 1 2)) 1)) (=> (= (first_3_3 (pair_3_3 1 2)) 1) (and (=> (= (ControlFlow 0 2) (- 0 3)) (= (second_3_3 (pair_3_3 1 2)) 2)) (=> (= (second_3_3 (pair_3_3 1 2)) 2) (=> (= (ControlFlow 0 2) (- 0 1)) (forall ((p@@0 T@Pair_15_16) (q T@Pair_15_16) ) (!  (=> (and (= (first_3_3 p@@0) (first_3_3 q)) (= (second_3_3 p@@0) (second_3_3 q))) (= p@@0 q))
 :qid |test2bpl.15:20|
 :skolemid |3|
)))))))))
(let ((PreconditionGeneratedEntry_correct  (=> (= (ControlFlow 0 5) 2) anon0_correct)))
PreconditionGeneratedEntry_correct)))
))
(check-sat)
(pop 1)
; Valid
(get-info :rlimit)
```
If I run `z3 test2.model`, I get - unsat, unsupported, ; :rlimit line: 48 position: 1
Removing the last line of the file eliminates the rlimit line error.
Copying the model file to my local system and running with local z3 (v4.4.1) returns the same issue.

This seems likely to be a mismatch in version to me, given that boogie works perfectly fine for this program on my local system. I have tried a few other simple boogie programs, and get this error for all of them.

When I run with the same arguments on my local system, the model file generated is quite different (has 153 lines), and does not have the last (get-info rlimit) line, which allows boogie to successfully verify.

It would be great if anyone could help me with this issue, thanks!

**Comment by shazqadeer** [comment] 2023-10-04 19:47
I agree that the problem is likely due to a mismatch between Boogie and Z3. To debug further, you could compare (1) the Boogie version in Docker and your local machine, and (2) the Z3 version in Docker and your local machine.

**Comment by shazqadeer** [comment] 2023-10-17 14:29
Closing this issue. Please reopen if you need further investigation from our end.

**Closed by shazqadeer** 2023-10-17 14:29 UTC
