### ISSUE TITLE
Unexplainable absence of Model and `{:print}` instructions

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#620] opened 2022-09-17 07:13 UTC
This [output.bpl](https://github.com/boogie-org/boogie/files/9591161/output.bpl.zip) generated by the Move Prover does not produce any model or other output. The failures it reports are justified, but all the metadata we would expect (model as well as output from `assume {:print ..}`) is missing.

This is how this is run: 

```
boogie -doModSetAnalysis -monomorphize -printVerifiedProceduresCount:1 -printModel:1 -enhancedErrorMessages:1  -proverOpt:O:model_validate=true -proverOpt:PROVER_PATH=/Users/wrwg/bin/z3 -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:4 -errorLimit:1 output.bpl
```

**Comment by wrwg** [comment] 2022-09-17 07:20
Boogie version used is 2.15.7

**Comment by wrwg** [comment] 2022-09-17 16:31
@shazqadeer

**Comment by shazqadeer** [comment] 2022-09-23 02:28
I am unable to reproduce your problem. When I run the file you supplied through the latest Boogie (version in master), I see both the augmented execution trace and the model being generated in the output.

Let me suggest a small experiment to debug further.
1. Build the latest Boogie on your machine.
2. Run Boogie on the small example at Test/test15/trace0.bpl. Make sure you use the options specified in the comment at the top of trace0.bpl.
3. Check if you get the same output as Test/test15/trace0.bpl.expect.

**Comment by wrwg** [comment] 2022-09-23 03:28
This is very strange. If I build boogie with Rider in fact everything seems fine. If I execute the installed boogie not. Both boogies have the same version:

```
~/boogie/play (master)> /Users/wrwg/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver -version
Boogie program verifier version 2.15.7.0, Copyright (c) 2003-2014, Microsoft.
~/boogie/play (master)> boogie -version 
Boogie program verifier version 2.15.7.0, Copyright (c) 2003-2014, Microsoft.
~/boogie/play (master)> which boogie
/Users/wrwg/.dotnet/tools/boogie
```

I tried to reinstall:

```
~/boogie/Source (master)> ~/.dotnet/dotnet  tool update --tool-path ~/.dotnet/tools/ Boogie 
Tool 'boogie' was reinstalled with the latest stable version (version '2.15.7').
```

But the re-installed Boogie has the same problem.

Using the following dotnet:

```
~/boogie/Source (master)> ~/.dotnet/dotnet  --version                                      
6.0.400
```

I'm not sure whether Rider uses the same runtime than this. Also notice this is on Apple Silicon.

**Comment by wrwg** [comment] 2022-09-23 17:17
On this example, both my local boogie and the build Boogie generate the same output, which is also the same as the expect.

This confirms the specifically strange thing here: we do not see in our Move prover usage this problem all the time. In fact, all our baseline tests which heavily depend on that Boogie is doing things right here work fine. We only have particular cases where it is happening (like the one attached to this issue).

**Comment by shazqadeer** [comment] 2022-09-23 17:34
Does the problem happen deterministically on the attached file? Suppose you run Boogie 100 times on that file. Do you see the faulty behavior all the time?

**Comment by wrwg** [comment] 2022-09-25 03:54
Interesting result... 

I use this:

```
#!/bin/zsh

BOOGIE=/Users/wrwg/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver

for ((i = 0; i < 100; i++)); do 
  echo "run $i"
  ${BOOGIE} -doModSetAnalysis -monomorphize -printVerifiedProceduresCount:1 -printModel:1 -enhancedErrorMessages:1  -proverOpt:O:model_validate=true -proverOpt:PROVER_PATH=/Users/wrwg/bin/z3 \
            -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:4 -errorLimit:1 output.bpl > y;
  diff x y || exit 22
done
```

Then I tried both with my locally compiled (as above) and the installed version.

All produce the same output (locally compiled correct). However:

- The installed boogie does not get further than round 7-9. After that the boogie hangs and can only be terminated with kill -9
- The locally compiled boogie goes up to round 25 but then hangs just as the above one.

Perhaps the hanging (which is not in Z3 -- when this happens, Z3 has terminated) is the cause for the original problem I see. Nevertheless, with the script above, you should be able to reproduce (though it certainly is non-deterministic -- looks like a hard bug).

Thanks for your help Shaz!

**Comment by wrwg** [comment] 2022-09-28 15:29
Can we perhaps just release a new boogie in the hope this fixes it?

**Comment by shazqadeer** [comment] 2022-09-28 16:31
@keyboardDrummer: I am wondering if you might have any idea about what could be causing this nondeterministic behavior. I recall there were many changes in the part of the implementation that orchestrates the interaction with the SMT solver. If you look at this thread, perhaps it will ring a bell.

**Comment by shazqadeer** [comment] 2022-09-29 02:32
@wrwg : I just tried running your script on output.bpl on my Mac laptop. But I don't see any hang even after 100 iterations. I am running with Z3 version 4.8.13. What is your version?

One possible explanation for the behavior you are seeing is that the Z3 process crashes for some reason on your machine and after that Boogie hangs waiting for output from Z3.

**Comment by wrwg** [comment] 2022-09-29 21:28
We are using z3 4.11.0.

**Comment by wrwg** [comment] 2022-09-30 03:35
So I need to find a temporary solution for this as the Move prover is basically not working. We can consume Boogie temporarily from a fork, while we are still trying to nail this down.

Can you give me a hint how to build a release in my fork? I have Rider. I tried 'publish' from the Boogie project drop down but as far as I see I get only a bunch of dlls.

**Comment by shazqadeer** [comment] 2022-09-30 04:29
On my Mac also, only dlls are generated. I run Boogie as follows from a script:
```
dotnet /Users/shaz/Source/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll $@
```

By the way, you should also be able to build from the command line as follows:
```
dotnet build /Users/shaz/Source/boogie/Source/Boogie.sln
```

I also released Boogie v2.15.8 which is the snapshot of master right now.

**Comment by wrwg** [comment] 2022-09-30 06:31
I was wondering how I can create my own `mvp-boogie` release to distribute to users via my fork of github. We have done this with Z3 before: you basically create in your fork of the repo a release which can than be consumed by users. It seems I need to go via some .Net appstore for this? Alternative would be a standalone single executable.

In any case, think you for releasing, that makes this unnecessary to resolve right now.

**Comment by wrwg** [comment] 2022-10-04 06:45
Wanted to report that upgrading to this new Boogie version solved our problem. It appears we have no idea why.

Another behavior we experiencing with boogie called from the Move prover are sporadic SIG_TRAP. 

I tend to believe the problems here are related to the .Net implementation on Mac silicon: all of them. (Missing outputs, non-termination, SIG_TRAP). So basically I wonder how we can get off .Net. Is there a reliable way to compile a C# program into a standalone binary? @RustanLeino

**Comment by shazqadeer** [comment] 2022-10-15 15:24
I don't know of any way to run Boogie independently of .Net Core. One would hope that because the hardware is new, these are all teething problems that will get sorted out.

It looks like you are unblocked. So I am closing this issue.

**Closed by shazqadeer** 2022-10-15 15:24 UTC
