### ISSUE TITLE
Equivalent expression fails assert

### ISSUE THREAD

**Issue by mmccoyd** [boogie-org/boogie#9] opened 2015-04-28 05:43 UTC
I am trying to zero a page. The first ensure below passes an assert, but the second does not. I may be missing something, but I thought to pass it on.

  ensures (forall a : bv8 :: a[8:4] == page ==> mem[a] == 0bv8);
  ensures (forall low : bv4 ::            mem[page ++ low] == 0bv8);

Test code with come comments and context is below. 

This is Boogie 2.3.0.61016 on Mono 3.2.8 on Debian 3.2.8+dfsg-10.

--Michael

/* Memory is an 8 bit address space of bytes.
   Providing 2^4 = 16 'pages' of 16 bytes each.
*/

type Byte = bv8;
type Addr = bv8;
type Ram = [Addr] Byte;
type Page = bv4;

var mem : Ram;

/* Zero a page, leave others unchanged. */
procedure zeroPage(page : Page);
  modifies mem;
  // Zero bytes of page
  // First version passes assert below, it 'mirrors' the ensures for unchanged.
  // Second version fails it.
  //ensures (forall a : Addr :: a[8:4] == page ==> mem[a] == 0bv8);
  ensures (forall low : bv4 :: mem[page ++ low] == 0bv8);

  // Other pages unchanged.
  ensures (forall a : Addr :: a[8:4] != page ==> mem[a] == old(mem)[a]);

procedure hv()
   modifies mem;
{
call zeroPage(2bv4);

// test page is zeroed
assert (forall a: Addr :: a[8:4] == 2bv4 ==> mem[a] == 0bv8);
}

**Comment by delcypher** [comment] 2015-04-28 06:32
I believe the issue is that for the program above Z3 is returning ``unknown`` rather than ``sat`` or ``unsat`` so Boogie conservatively says that the assertion can fail. You can check that by passing ``-proverLog:queries.smt2`` to Boogie and then passing that file to Z3 manually.

I tried both versions of your program with my proto-type symbolic execution tool for Boogie and both versions are shown to be correct.

As for the reason to why Z3 is behaving this way I don't know because I don't have a great understanding of how quantifiers are handled internally. However I suspect using that the first version of your program is much simpler to prove because on the only path in the program, ``page`` is known to be ``2bv4`` so you're essentially asking given that the following formula is assumed to be true

```
forall a : Addr :: a[8:4] == 2bv4 ==> mem[a] == 0bv8
```

can the assert

```
forall a : Addr :: a[8:4] == 2bv4 ==> mem[a] == 0bv8
```

be violated? Since you are asserting the formula that you assumed to be true is true it obviously cannot be violated.

**Comment by delcypher** [comment] 2015-04-28 22:17
I'm going to close this issue. Please re-open it if you have more questions.

**Closed by delcypher** 2015-04-28 22:17 UTC
Labels: question
