### ISSUE TITLE
Error when parsing models with maps of floating point values

### ISSUE THREAD

**Issue by classner** [boogie-org/boogie#110] opened 2019-01-17 11:05 UTC
This is another issue related to PR #107 concerning models for maps with floats. It seems boogie can't parse model outputs (at least from) z3 for this case. For example, this program obviously fails to verify:

```
procedure Exp2(a:[int]float24e8)
{
  assert a[0] > 0x0.0e0f24e8;
}
```

When running boogie just as `%boogie Exp2.bpl`, it correctly states that the assertion might not hold and terminates. However, when adding `/printModel:4`, it raises an error, stating

```
Prover error: Model parsing error: Invalid model: unidentified line, at line 2 (a -> |T@[Int](_ FloatingPoint 8 24)!val!0|)
Prover error: Could not parse any models
```

Adding `/printModelToFile:out.txt` also doesn't help, since it apparently wants to parse the model first.

**Comment by zvonimir** [comment] 2019-01-17 11:13
@liammachado : please take a look at this one. Maybe also create a regression for it.

**Comment by liammachado** [comment] 2019-01-17 16:33
I don't think that this error is being caused by PR #107, since I am receiving the same error with the master branch.

**Comment by classner** [comment] 2019-01-17 20:38
Sorry @liammachado, I thought only #107 was integrating the floating point syntax (I'm new to the project).

**Comment by zvonimir** [comment] 2019-02-19 14:19
@liammachado Please take a look at this problem even if it was not caused by your recent pull request. We should try to fix it no matter what. It is unclear to me whether parsing of models is not working for floating-points at all, or is it something specific about this benchmark.

**Comment by shazqadeer** [comment] 2019-12-19 05:37
@zvonimir : Any updates?

**Comment by zvonimir** [comment] 2019-12-19 17:19
I'll look into this more carefully next week.

**Comment by zvonimir** [comment] 2020-02-05 20:30
@shaobo-he : Please take a look into this and report back your findings. We should get this fixed.

**Comment by shazqadeer** [comment] 2020-07-15 00:37
Neither @liammachado nor @shaobo-he has responded.

@zvonimir : Should we close this issue going on record that we won't fix the problem now?

**Comment by shaobo-he** [comment] 2020-07-15 00:45
> Neither @liammachado nor @shaobo-he has responded.
> 
> @zvonimir : Should we close this issue going on record that we won't fix the problem now?

I recalled that I concluded it's not going to be a trivial fix. How about letting me try to fix it this week? If I can't come up with anything by Monday, we'll close this issue.

**Closed** 2020-07-15 19:39 UTC
