### ISSUE TITLE
Problems updating to the latest release of Z3

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#47] opened 2016-11-15 23:10 UTC
Team Z3 released version 4.5.0 last week, containing a bunch of bug fixes and improvements. It would be great for Boogie to keep tracking Z3 if possible. We tried this update on our end, but we are encountering many unexpected results in Boogie regressions. It seems that this problem has something to do with model extraction in Boogie.
We (meaning team SMACK) would greatly appreciate if a Boogie expert could take a look at this. Thanks!

**Comment by shazqadeer** [comment] 2016-11-16 01:46
Can you send me a particular Boogie file (or point me to one in the repository) that manifests this problem?  Where can I get the 4.5.0 Z3 binary so I can reproduce the problem?

**Comment by zvonimir** [comment] 2016-11-16 01:54
You can get the latest Z3 binary (4.5.0) from here: https://github.com/Z3Prover/z3/releases
If you run Boogie regressions with this new Z3, you should see a number of them returning unexpected results.

**Comment by shazqadeer** [comment] 2016-11-16 03:53
I tried the x86 version of z3.exe.

C:\Users\qadeer\Work\boogie\Test\livevars>..\..\Binaries\z3.exe /version
Z3 version 4.5.0 - 32 bit

I did "lit ." in the Test folder and got the following output.  Is this what you get?

********************
Failing Tests (2):
    Boogie :: livevars/daytona_bug2_ioctl_example_2.bpl
    Boogie :: test15/CaptureState.bpl

  Expected Passes    : 358
  Expected Failures  : 2
  Unsupported Tests  : 83
  Unexpected Failures: 2

1 warning(s) in tests.

**Comment by zvonimir** [comment] 2016-11-16 04:47
I am running on Linux with x64 version of Z3. I get:
```
  Expected Passes    : 196
  Expected Failures  : 2
  Unsupported Tests  : 83
  Unexpected Failures: 164
```
I guess I can try 32-bit version of Z3 as well.

**Comment by zvonimir** [comment] 2016-11-16 04:51
Same thing. And this is an example of the kinds of error messages I've been getting:
```
zvonimir@betina:~/projects/smack-project/boogie/Test/civl$ boogie -noinfer -typeEncoding:m -useArrayTheory DeviceCache.bpl
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_release_Init' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_release_release' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'FailurePreservationChecker_release_release' timed out after -1 seconds
(0,0): Verification of 'CommutativityChecker_acquire_release' timed out after -1 seconds
(0,0): Verification of 'GatePreservationChecker_release_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'FailurePreservationChecker_WriteCurrsize_release' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'FailurePreservationChecker_WriteNewsize_release' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'FailurePreservationChecker_ReadNewsize_release' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'FailurePreservationChecker_ReadCurrsize_release' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_acquire_Init' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_acquire_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_WriteCurrsize_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_WriteNewsize_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_ReadNewsize_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'GatePreservationChecker_ReadCurrsize_acquire' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_ReadNewsize_Init' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_ReadNewsize_WriteNewsize' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_ReadCurrsize_Init' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
(0,0): Verification of 'CommutativityChecker_ReadCurrsize_WriteCurrsize' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(27,32): Verification of 'Yield_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(35,32): Verification of 'YieldToReadCache_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(43,32): Verification of 'YieldToWriteCache_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(51,32): Verification of 'Allocate_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(59,32): Verification of 'main_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(84,32): Verification of 'Thread_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(95,32): Verification of 'Read_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(135,32): Verification of 'WriteCache_1' timed out after -1 seconds
Prover error: Unexpected prover response getting labels: labels
DeviceCache.bpl(156,32): Verification of 'ReadCache_1' timed out after -1 seconds

Boogie program verifier finished with 11 verified, 0 errors, 28 time outs
```

**Comment by shazqadeer** [comment] 2016-11-16 15:23
That is strange.  I am unable to repro this behavior.

@RustanLeino : Can you try to repro at your end?

**Comment by zvonimir** [comment] 2016-11-16 19:22
I tried this on several Linux (Ubuntu 14.04) machines and I encounter this same problem on all of them, with both 32 and 64 bit versions of Z3. I will try a more recent Ubuntu 16.04 next.

**Comment by delcypher** [comment] 2016-11-16 19:58
@zvonimir Trying newer Ubuntu versions is unlikely to fix this. The error message

```
Prover error: Unexpected prover response getting labels: labels
```

means whilst parsing the response from Z3 something went wrong. You should try finding (grep for the error message) where this error message gets emitted and from there work out what Z3 is emitting that Boogie doesn't like.

**Comment by bkragl** [comment] 2016-11-16 21:48
I agree with @delcypher, the error messages indicate some problem in parsing Z3 output. However, it would be quite strange that this alone causes such fluctuating test runs. I just did three runs on a recent x64 Ubuntu machine and my "Expected Passes" increased from 265, to 267, to 269. I'm afraid of the fourth run failing my linear extrapolation.

**Comment by zvonimir** [comment] 2016-11-16 22:07
We are scrambling to prepare for SV-COMP, and we have other more pressing issues on our plate at this point. So for now we will revert SMACK to the old release of Z3 that reliably works (I think at least :)).
Having said that, I think that in the long term we should try to keep Boogie updated with the latest stable release of Z3, and so I'll try to get back to this. You are more than welcome to explore this further.
I think that if we can at least roughly figure out what is going on, we could also engage with Z3 guys to help us out if needed.

**Comment by shazqadeer** [comment] 2016-11-16 22:20
It would help if you could repro this issue on Windows.

**Comment by zvonimir** [comment] 2016-11-16 22:41
Yeah, I know, but my hunch is that this one cannot be reproduced on Windows. This is likely something related to Linux+mono+Boogie+new Z3 combination.

**Comment by delcypher** [comment] 2016-11-16 22:52
I think I've found the issue. Fix is incoming.

**Comment by delcypher** [comment] 2016-11-16 23:06
The problem is when Boogie emits

```
(set-option :TIMEOUT 0)
```

to Z3. Z3's behaviour seems to have changed.

I think it's related to

https://github.com/Z3Prover/z3/commit/a6e1c70eab988de59560c34a4222c99ce80e2feb.

For now the simplest fix it just to not set the option if there is no timeout. I should raise the issue with the Z3 guys because I'm not sure if this change is desirable.

**Comment by delcypher** [comment] 2016-11-16 23:18
I've filled an issue with the Z3 guys ( https://github.com/Z3Prover/z3/issues/791 ) and I'll implement a hacky fix for this in Boogie for now.

**Comment by zvonimir** [comment] 2016-11-16 23:23
Thanks a lot!

**Closed** 2016-11-17 01:14 UTC
