### ISSUE TITLE
Boogie Visual Studio build doesn't work with up-to-date versions of Visual Studio

### ISSUE THREAD

**Issue by alexanderjsummers** [boogie-org/boogie#164] opened 2019-11-29 16:45 UTC
Compilation doesn't work according to the instructions on the home page. It's possible to compile Boogie using somewhat similar steps to the linux build, on the command-line. I haven't yet found a way to get the same effect within Visual Studio itself. I suspect VS 2017 might have been the last version these instructions worked for; they don't seem to work for 2019 (including e.g. some menu options not existing).

**Comment by bkragl** [comment] 2019-11-29 17:53
There was a recent cleanup of the configurations in the project files. Just
to make sure this is not the problem, could you try building in VS on your
setup at this commit:
c099a60

And make sure you do a nuget restore before.

**Comment by shazqadeer** [comment] 2019-12-01 04:39
I believe this problem was introduced by cleanup of configurations. I reverted the very last commit (https://github.com/boogie-org/boogie/commit/29e0bfc6da95542f44ab2230d74e098c1c590bbc) on that topic and the problem seems to be fixed.  I will have to attack the configuration cleanup again.  Please verify at your end that the problem is indeed fixed.

**Comment by bkragl** [comment] 2019-12-02 10:04
I can now confirm that the compilation problems were due to the configuration changes. With the current state of master (i.e., commit b608146) compilation in Visual Studio 2019 works again according to the instructions (module the menu option `Enable NuGet Package Restore` now being called `Restore NuGet Packages`). So I'm closing this and PR #162.

Note that I first encountered the following error:

```
Couldn't process file Main.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.
```

Seems to be some Windows security mechanism that blocks the file (I downloaded the source code as ZIP). You have to go to the file properties and select `Unblock`.

**Closed by bkragl** 2019-12-02 10:04 UTC
